title: Pair framework
description: a lightweight PHP framework as the air
show_downloads: true
theme: jekyll-theme-cayman
url: "https://viames.github.io"
baseurl: "/pair"
repository: "viames/pair"
homepage_url: "https://viames.github.io/pair/"
wiki_url: "https://github.com/viames/pair/wiki"
issues_url: "https://github.com/viames/pair/issues"
